# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kevin Chan
title: Data Science Undergraduate
email: kevinchanfsa@gmail.com
website: https://alutare.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: Alutare
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: chan-wei-wen-kevin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kevin and I'm currently a 3rd year undergraduate at the National University of Singapore (NUS), pursuing a BSc (Hons) in Data Science and Analytics. I enjoy building full-stack data solutions, from processing data to creating dashboards and interfaces that turn insights into action. It's fulfilling to see these end-to-end systems make a real impact for users.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: NUS Datathon 2025
        link: https://github.com/Alutare/NUS_Datathon_2025
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Alutare/NUS_Datathon_2025
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        description: | # this will include new lines to allow paragraphs
          My team won 1st place out of 94 teams by developing a machine learning model using XGBoost to classify business corporate ownership into three categories, achieving a 91% accuracy rate and a 91% weighted F1-score.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hewlett Packard (HP)
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Science Intern
        caption: January 2025 - June 2025
        quote: >
        description: | # this will include new lines to allow paragraphs
            Developed solutions such as manufacturing analytics dashboards and machine learning applications to track, analyze and visualize outgoing quality of supplies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National University of Singapore
        caption: 2023 - 2027
        sub_title: BSc (Hons) Data Science and Analytics
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
